### ISSUE TITLE
Allow to send "id" in sign up request

### ISSUE THREAD

**Issue by gr2m** [gr2m/account-rest-api#15]
We need support a client-generated ID for for Hoodie. JSON API [explicitly supports client-generated resource IDs](http://jsonapi.org/format/#crud-creating-client-ids), so let’s put it into the spec, that it’s allowed, but not required of course

**Comment by gr2m** [comment]
Also mention that other attributes besides `"username"` and `"password"` may be sent. For example, the Hoodie Clients sends a `"createdAt"` property which is the timestamp the user account was created on the client

**Comment by barretodaniel** [comment]
I'm going to work on this one. Are the attributes that can be sent documented anywhere?

**Comment by gr2m** [comment]
> Are the attributes that can be sent documented anywhere

There can be any attributes, it’s not part of the spec, it depends on the apps / implementations. For the spec I’d just mention that the attributes can differ, username and password is just an example
