### ISSUE TITLE
Adjust POST /requests spec

### ISSUE THREAD

**Issue by gr2m** [gr2m/account-rest-api#16]
current state is at
http://docs.accountjsonapi.apiary.io/#reference/requests/request-collection/create

source is here:
https://github.com/hoodiehq/account-json-api/blob/master/apiary.apib#L725

---
- [x] start a PR
- [x] Add 201 response: `links.self` is optional. If no resource is persisted in the database, it won't be set (not relevant anymore, see comment below)
- [x] specify a response if request handler is not implemented (403 maybe)?
- [x] review & merge

**Comment by patriciagarcia** [comment]
As discussed with @gr2m, we'll always return `links.self` but until the persistence layer for requests is implemented, `GET /requests/<request_id>` will return `404`.

> - [ ] Add 201 response: links.self is optional. If no resource is persisted in the database, it will not be set
