### ISSUE TITLE
Questions about URLs and API response status codes

### ISSUE THREAD

**Issue by patriciagarcia** [gr2m/account-rest-api#3]
Hey folks, I have a lot of questions about the [API](http://docs.accountrestapi.apiary.io) URLs and returned status codes, also, it seems to me that a lot of possible error responses are omitted from the API, so here is a compilations of questions and feedback about the current defined API for further discussion.

Disclaimer: I am focusing first on the "User" (i.e. non admin) part of the API, so this discussion is only about that part.
### Sign in `PUT /session`

Possible responses:
- session created: `201`
- invalid credentials provided: `401`
- wrong `type` provided in the request (`data.type`): `409`*
- a user is logged in already (there is already an active session):  ?
### Check session `GET /session`

Possible responses:
- OK: `200`
- invalid auth header: `401`
- no active session: `401`/`404`?**
### Sign out `DELETE /session`

Possible responses:
- delete worked: `204`
- invalid auth header: `401`
- no active session: `401`/`404`?**
### Sign up `PUT /session/account`

About the URL:
- shouldn't that be `POST /accounts` (this is the URL for admins)
- it seems weird to me to create a session using `PUT /session/account` when the session does not exist (since, if the session exist, then we already have an account for it, haven't we?)

Possible responses:
- account created: `201`
- wrong `type` provided in the request (`data.type`): `409`*
- a user is logged in already (there is already an active session, with a corresponding account):  ?
### Fetch user account `GET /session/account`

Possible responses:
- OK: `200`
- invalid auth header: `401`
- no active session: `401`/`404`?**
### Change user account `PATCH /session/account`

Possible responses:
- OK: `204`
- invalid auth header: `401`
- no active session: `401`/`404`?**
- updating the user [infringes some server-enforced constraints](http://jsonapi.org/format/#crud-updating-responses-409): `409` (this might not be relevant for us)
- `type` and `id` provided in the request don't match (`data.type`): `409`***
### Close account `DELETE /session/account`

Possible responses:
- OK: `204`
- invalid auth header: `401`
- no active session: `401`/`404`?**
### Fetch profile `GET /session/account/profile`

Possible responses:
- OK: `200`
- no profile available: `200` with `null` as primary data. See [JSON API spec](http://jsonapi.org/format/#fetching-resources-responses).
- invalid auth header: `401`
- no active session: `401`/`404`?**
### Create profile `PUT /session/account/profile`

Possible responses:
- profile created: `201`
- invalid auth header: `401`
- no active session: `401`/`404`?**
- wrong `type` provided in the request (`data.type`): `409`*
- a profile is available already:  ?
### Update profile `PATCH /session/account/profile`

Possible responses:
- OK: `204`
- invalid auth header: `401`
- no active session: `401`/`404`?**
- updating the user [infringes some server-enforced constraints](http://jsonapi.org/format/#crud-updating-responses-409): `409` (this might not be relevant for us)
- `type` and `id` provided in the request don't match (`data.type`): `409`***

*This is [mentioned in the JSON API spec](http://jsonapi.org/format/#crud-creating-responses-409) referring to creating users with `POST`, I guess it also applies to `PUT`?

**Some considerations about this one:
- if there is no active session, then our auth credentials are not the right one, so response should be `401`?
- `404` can be interpreted as: URL doesn't exist, but if the URL doesn't exist, we can't really use `PUT` for the creation of the resource, can we?

**\* See [here](http://jsonapi.org/format/#crud-updating-responses-409).

@gr2m, @tthew, @karlwestin comments?

**Comment by gr2m** [comment]
This is great feedback!!!

### Sign in `PUT /session`

> wrong type provided in the request (data.type): 409*

The type is `session` and is implicitly set by the URL. I don't know how a `PUT /session` request could possibly cause a conflict. The same holds for `PUT /session/account`, the type is set implicitly, it's not passed in request body's JSON

> a user is logged in already (there is already an active session): ?

When in doubt, do a `400` :) But this response would require a different request in which `Authorization` header is sent, which should be forbidden for that route

### Check session `GET /session`

> no active session: 401/404?**

`404` is the right code. The resource doesn't exist. If the session for the past bearer token does not exist anymore, then it's gone, like a CouchDB document that once existed but now not anymore. 

That's the same for all the `**` notes

### Sign up `PUT /session/account`

> About the URL:
> - shouldn't that be POST /accounts (this is the URL for admins)
> - it seems weird to me to create a session using PUT /session/account when the session does not exist (since, if the session exist, then we already have an account for it, haven't we?)

I think you meant "it seems weird to me to create **an account**", not a session, right? 

The thinking behind this is: a session always belongs to an account. We could also do `PUT /account` but `PUT /session/account` makes it more clear I think, and aligns better with the `?include` query param from the JSON API spec.

`POST /accounts` would imply that I'd then get a URL like `/accounts/123` that I can access. But APIs should always be user-centric, so there is no need to expose the user ID in the URL, a user can have only one account, and a user cannot access other accounts.

Admins, on the other side, can access all accounts, so they have the traditional CRUD routes for `/accounts`. 

### Fetch profile `GET /session/account/profile`

> Possible responses:
> - no profile available: 200 with null as primary data. See JSON API spec.

Good catch, I agree. With that, it might make sense to remove the `PUT /session/account/profile` entirely, the `PATCH` should be enough, as we can imply that if there is an account, there is always a profile, too.

I wonder if we could avoid confusion by returning 

``` json
{
  "type": "accountProfile",
  "attributes": {}
}
```

instead of `null`?

**Comment by karl-ehealth** [comment]
I don't agree on `GET /session` 
I think that this endpoint is not really a rest endpoint (if you were calling /session/{token} it would be...). 
I think it creates problems for writing a more general API layer.
Couch returns 200 with a null user. and if you have `require_valid_user` set it returns 401. In my opinon, this is easier to reason about when creating an API client

**Comment by patriciagarcia** [comment]
Thanks @gr2m and @karl-ehealth!  my comments to the comments inline:

### Sign in `PUT /session`

> > wrong type provided in the request (data.type): 409*
> 
> The type is session and is implicitly set by the URL. I don't know how a PUT /session request could possibly cause a conflict. The same holds for PUT /session/account, the type is set implicitly, it's not passed in request body's JSON

This is [a JSON API thing](http://jsonapi.org/format/#crud-creating-responses-409), the `type` is mandatory, not implicit. What the specification says is that "A server MUST return `409 Conflict` when processing a `POST` request in which the resource object's `type` is not among the type(s) that constitute the collection represented by the endpoint."

I assume that applies too when the `type` is missing? Or maybe in that case `403 Forbidden` with an error explaining that `type` should be provided is better?

> > a user is logged in already (there is already an active session): ?
> 
> When in doubt, do a 400 :) But this response would require a different request in which Authorization header is sent, which should be forbidden for that route

I was wondering if that should be `409` but I guess that would be [if the session id would be provided in the request](http://jsonapi.org/format/#crud-creating-responses-409), which is not. So `403` if auth is provided sounds good to me.

> > no active session: 401/404?**
> 
> 404 is the right code. The resource doesn't exist. If the session for the past bearer token does not exist anymore, then it's gone, like a CouchDB document that once existed but now not anymore.
> 
> That's the same for all the *\* notes

IMHO both `401` and `404` are true in different ways: the session does not exist, but as the session does not exist, the auth is invalid, it's more a matter of which one of the two you check first and I think, for security reasons, auth should be checked first, in general. As @karl-ehealth mentioned, `401` is also more in line with CouchDB behaviour, when `require_valid_user` is set. 

Also I was discussing this with @tthew and there is a bit of a contradiction with using `PUT` (that implies that the URL for the resource exists) and then returning `404 Not Found`. It's sort of acknowledging that the URL exists and then saying in the respond that it doesn't.

## Fetch profile `GET /session/account/profile`

> > Possible responses:
> > - no profile available: 200 with null as primary data. See JSON API spec.
> 
> Good catch, I agree. With that, it might make sense to remove the `PUT /session/account/profile` entirely, the `PATCH` should be enough, as we can imply that if there is an account, there is always a profile, too.
> 
> I wonder if we could avoid confusion by returning
> 
> ```
> {
>   "type": "accountProfile",
>   "attributes": {}
> }
> ```
> 
> instead of null?

Sounds good, it makes sense to me that an account has an associated profile, even if it's empty.

**Comment by patriciagarcia** [comment]
Summarizing the comments and offline discussions..
[UPDATED after last comments]

## Session

### Sign in `PUT /session`

Possible responses:
- session created: `201`
- invalid credentials provided: `401`
- wrong `type` provided in the request (`data.type`): `409`
- no `type` provided in the request (`data.type`): `409`
- a user is logged in already (an auth token is provided):  `403`

### Check session `GET /session`

Possible responses:
- OK: `200`
- invalid auth header: `401`
- no active session: `401`

### Sign out `DELETE /session`

Possible responses:
- delete worked: `204`
- invalid auth header: `401`
- no active session: `401`

## Account

### Sign up `PUT /session/account`

Possible responses:
- account created: `201`
- wrong `type` provided in the request (`data.type`): `409`
- a user is logged in already (there is already an active session, with a corresponding account):  `403`

### Fetch user account `GET /session/account`

Possible responses:
- OK: `200`
- invalid auth header: `401`
- no active session: `401`

### Change user account `PATCH /session/account`

Possible responses:
- OK: `204`
- invalid auth header: `401`
- no active session: `401`
- updating the user [infringes some server-enforced constraints](http://jsonapi.org/format/#crud-updating-responses-409): `409` (this might not be relevant for us)
- `type` and `id` provided in the request don't match (`data.type`): `409`

### Close account `DELETE /session/account`

Possible responses:
- OK: `204`
- invalid auth header: `401`
- no active session: `401`

## Profile

### Fetch profile `GET /session/account/profile`

Possible responses:
- OK: `200` (profile can be empty)
- invalid auth header: `401`
- no active session: `401`

### Update profile `PATCH /session/account/profile`

Possible responses:
- OK: `204`
- invalid auth header: `401`
- no active session: `401`
- updating the user [infringes some server-enforced constraints](http://jsonapi.org/format/#crud-updating-responses-409): `409` (this might not be relevant for us)
- `type` and `id` provided in the request don't match (`data.type`): `409`

**Comment by gr2m** [comment]
You are right about the `type`, it must be send in requests, so the `409` responses make sense to me now, cheers :)

**Comment by gr2m** [comment]
This is great, I agree with all now, thanks @patriciagarcia :)

### Sign Up `PUT /session/account`

> a user is logged in already (there is already an active session, with a corresponding account): 

I would per specification forbid to send an `Authorization` header in that request. And if no `Authorization` header is send, the server cannot now about an active session. If it's send it should respond with `403`, because the server understands everything in requests, but refuses to respond to it because of an invalid request ... ?

**Comment by patriciagarcia** [comment]
Oh yeah, of course, is the same thing as `PUT /session` with an auth header, I think I forgot to take the question mark out of it, oops :). Summary updated with this.

**Comment by patriciagarcia** [comment]
Closing this, since the PR with the changes is already merged. Thanks for the feedback!
