### ISSUE TITLE
Remove Content-Type header from Profile Fetch

### ISSUE THREAD

**Issue by HipsterBrown** [gr2m/account-rest-api#6]
<img width="739" alt="screen shot 2015-11-21 at 3 00 46 pm" src="https://cloud.githubusercontent.com/assets/3051193/11320255/ba1709c0-9060-11e5-8404-845cb18ecc6e.png">

`GET` requests without a JSON payload/body do not require a Content-Type header since no content is being sent to the server. This should be removed from the documentation.

**Comment by gr2m** [comment]
:+1:  @HipsterBrown wanna send a PR for this?
